---
title: "DB_Estadistica"
author: "Anthony Jimenez"
date: "2024-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Librerias

install.packages("zoo")
library(zoo)
install.packages("dplyr")
library(dplyr)
library(readxl)
install.packages("gtsummary")
library(gtsummary)
install.packages("pastecs")
library(pastecs)
install.packages("summarytools")
library(summarytools)
install.packages("ggplot2")
library(ggplot2)
```


```{r}
# Se importa el archivo de excel el cual contiene el dataframe
# y se guarda en la variable World_Data

directorio <- getwd()
World_Data_Directorio <- file.path(directorio, "World_Data.xlsx")
World_Data <- read_excel(World_Data_Directorio)
World_Data_2 <- World_Data
```

```{r}
# Se obtiene un summary de las diferentes variables que componen
# el set de datos.

summary(World_Data)
```
```{r}
# Se decide reemplazar los valores N/A presentes en distintas entradas por el
# promedio de la variable.

promedios <- sapply(World_Data_2, function(x) if(is.numeric(x)) mean(x, na.rm = TRUE) else NA)
for (col in names(World_Data_2)) {
  World_Data_2[[col]][is.na(World_Data_2[[col]])] <- promedios[[col]]
}

# La existencia de valores N/A es debido a que no todos los paises reportan todos los años a las tres entidades de las cuales se obtienen los datos, esto debido a las distintas dinamicas geo-socio-politicas que se desarrollan en las distintas divisiones geograficas del mundo, asi como la calidad de las relaciones que existe entre los paises, o situaciones de guerra o crisis.
```

```{r}
# Se van a contar los N/A presentedes en la base de datos para asegurar
# de que no haya ninguno

conteo_NA <- colSums(is.na(World_Data_2))
print(conteo_NA)
```

```{r}
# Se carga la base de datos con los indices de felicidad y las categorias mediante las cuales se mide este.

Tabla_Felicidad_Directorio <- file.path(directorio, "DataForTable2.1 (1).xls")
Tabla_Felicidad <- read_excel(Tabla_Felicidad_Directorio)
```

```{r}
# Los valores que presenta la tabla de World_Data utiliza promedios que van desde # el rango del 2015 al 2018, por lo que se procede a trabajar Tabla_Felicidad, se # eliminan los años que no corresponden al promedio que se desea calcular. Ademas # se calcula el promedio y se genera una nueva tabla unicamente con los promedios # de las distintas variables

Tabla_Felicidad_Reducida <- Tabla_Felicidad[Tabla_Felicidad$year >= 2015 & Tabla_Felicidad$year <= 2018, ]

Tabla_Felicidad_Promedio <- Tabla_Felicidad_Reducida %>%
  group_by(`Country name`) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE))

Tabla_Felicidad_Promedio <- Tabla_Felicidad_Promedio %>%
  select(-year)
```

```{r}
# Se eliminan de World_Data_2 las variables "social_support", "freedom" y 
# "generosity", esto con el fin de agregar los promedios obtenidos de 
# Tabla_Felicidad_Reducida.

World_Data_2 <- World_Data_2 %>%
  select(-social_support, -freedom, -generosity)
```

```{r}
# Se unen los dos df, realizando una comparacion entre country y Country name,
# ademas se omiten los paises que no cuentan con una entrada en 
# Tabla_Felicidad_Promedio

World_Data_3 <- merge(World_Data_2, Tabla_Felicidad_Promedio, by.x = "country", by.y = "Country name")
```

```{r}
# Se decide reemplazar los valores N/A presentes en distintas entradas por el
# promedio de la variable.
# Se van a contar los N/A presentedes en la base de datos para asegurar
# de que no haya ninguno, además se va a realizar un summary de esta.
# Como se explico de forma previa la existencia de valores N/A es debido a que no todos los paises reportan todos los años a las tres entidades de las cuales se obtienen los datos, esto debido a las distintas dinamicas geo-socio-politicas que se desarrollan en las distintas divisiones geograficas del mundo, asi como la calidad de las relaciones que existe entre los paises, o situaciones de guerra o crisis.

promedios <- sapply(World_Data_3, function(x) if(is.numeric(x)) mean(x, na.rm = TRUE) else NA)
for (col in names(World_Data_3)) {
  World_Data_3[[col]][is.na(World_Data_3[[col]])] <- promedios[[col]]
}
conteo_NA <- colSums(is.na(World_Data_3))
print(conteo_NA)
summary(World_Data_3)
```

```{r}
# En la estructura que presenta "World_Data_3" se puede observar que cada
# variable va en una columna, no existe una combinación de distintas variables
# en la misma columna.
# A su vez cada observación es unica y sus valores estan distribuidos a lo largo
# de una unica fila
# Existe un identificador o key claro para cada una de las entradas, en este caso corresponde a la columna "country" que indica el país.
# Además queremos que todas las variables manejen valores numericos, asi que se va a reemplazar los valores de "income_class" por su factor, para de esta forma tener unicamente variables numericas.

# Ahora lo que vamos a realizar es un analisis descriptivo completo de la tabla, la forma mas sencilla de empezar este proceso es mediante la funcion "summary()", la cual me permite obtener distintos estadísticos de la tabla en cuestión.
# Se procede a utilizar dicha funcion.

World_Data_3 <- World_Data_3 %>%
  mutate(income_class = case_when(
    income_class == "Low income" ~ 0,
    income_class == "Lower middle income" ~ 1,
    income_class == "Upper middle income" ~ 2,
    income_class == "High income" ~ 3
  ))

str(World_Data_3)
summary(World_Data_3)
colnames(World_Data_3) <- tolower(gsub(" ", "_", colnames(World_Data_3)))


# Además vamos a eliminar la columna de país, ya que queremos conseguir una correlación entre las distintas variables, esta no aporta utilidad en una escala mayor.

Data_trabajar <- subset(World_Data_3, select = -country)


```



```{r}
# Con la data estructurada de la forma adecuada, podemos empezamos a buscar la relación existente entre los distintos marcadores con respecto a nuestro variable objetivo, en este caso life_ladder



# De la matriz de covarianza, podemos encontrar que tanta relación existe entre las distintas variables que forman la tabla, de forma que va a ser mas sencillo visualizar en que variables concentrar el estudio.
# Asi como la de correlacion, ya que al estar normalizada con valores que van desde -1 hasta 1, resulta mas sencilla observar las relaciones existentes

Tabla_covarianza = cov(Data_trabajar)
Tabla_correlacion = cor(Data_trabajar)

# Además se van a conseguir varios marcadores estadisticos con el fin de tener un entendimiento más completo de los datos y como estos se comportan de forma individual
Tabla_stats = stat.desc(Data_trabajar)
Tabla_descripcion = descr(Data_trabajar)
Df_resumen = dfSummary(Data_trabajar)
```
```{r}
variables <- setdiff(names(Data_trabajar), "life_ladder")
for(var in variables) {
  p <- ggplot(Data_trabajar, aes_string(x = var, y = "life_ladder")) +
    geom_point() +
    labs(x = var, y = "Life Ladder",
         title = paste("Gráfico de", var, "contra Life Ladder"))
  
  
  ggsave(filename = paste0("C:/Users/Anthony/Desktop/", var, "_vs_life_ladder.png"), plot = p)
}

```


